### ISSUE TITLE
Wrong number of icons in row

### ISSUE THREAD

**Issue by simonbcn** [emvaized/selecton-extension#25]
```
Google Chrome 98.0.4758.80
Selecton 3.5.1
```

I have set 5 icons per row in settings:

![2022-02-12_09-42_1](https://user-images.githubusercontent.com/428231/153704291-8aa6c670-4a6e-4041-ae50-2e9bae62d141.jpg)

But in the first row it always puts one more.

![2022-02-12_09-42](https://user-images.githubusercontent.com/428231/153704300-791a5a6a-6af6-4302-883d-6f83849a7448.jpg)

**Comment by emvaized** [comment]
Thanks for your report.
This issue is already fixed in the new version (`dev` channel here on GitHub), which will be released soon.

**Comment by emvaized** [comment]
This issue should be fixed in 3.5.5

**Comment by simonbcn** [comment]
No, it still fails.
![2022-02-18_12-16](https://user-images.githubusercontent.com/428231/154672770-7f78e163-a55c-4feb-a6f5-8541c109535d.png)

**Comment by emvaized** [comment]
Hm, so now the second row fails?

**Comment by simonbcn** [comment]
Yes.

> Hm, so now the second row fails?

Yes.

**Comment by emvaized** [comment]
Okay, I'll take a look

**Comment by emvaized** [comment]
Does the issue still persists for you in latest git version?

**Comment by simonbcn** [comment]
No, it is solved but the icons in second and more row are not aligned.
![2022-02-20_09-16](https://user-images.githubusercontent.com/428231/154834479-d9ac85ee-83bc-41f3-9f3f-08644b055947.png)

![2022-02-20_09-17](https://user-images.githubusercontent.com/428231/154834481-6eb699d3-d35e-4ed7-b83a-40c0325a869e.png)

**Comment by emvaized** [comment]
I think I got this, the issue was probably caused by disabled search options which still counted by script.
Please try out the new version, and if it won't be fixed I'll try another approach.

**Comment by simonbcn** [comment]
In my case there is no search engine disabled.

**Comment by emvaized** [comment]
Okay. Then, I just tried another approach I mentioned — the issue should be gone now (I guess).

**Comment by simonbcn** [comment]
Thanks. Yes, it works now.
